{% set name = "rainbowlog" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rainbowlog-{{ version }}.tar.gz
  sha256: 4c206fa699c3b4857c78befb5d0f7e74e74873a57343508d98d58bc85728978d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - constyle >=1.0.2,<2.0.0
    - importlib-metadata >=4.11,<5.0
    - python >=3.7

test:
  imports:
    - rainbowlog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abrahammurciano/rainbowlog
  summary: Format your python logs with colours based on the log levels.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - abrahammurciano
